# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    view:
        view_response_listener: true
        formats:
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
            - { path: '^/api/doc', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
